### ISSUE TITLE
Weiterentwicklung

### ISSUE THREAD

**Issue by sigi2345** [runsnbunsn/ioBroker.fontui#9]
Hallo,

wird es noch weiterentwickelt?
Gibt es noch mehr Icons, oder eine Möglichkeit eigene Icons einzubinden?

**Comment by runsnbunsn** [comment]
Hi!

sorry, habe die nachricht jetzt erst gesehen....
Ich komme mit den derzeitigen möglichkeiten/icons ganz gut aus, aber wenn die ideen/vorschläge hast können wir gerne reden, auch pull requests werden gerne angenommen.
Ich möchte das ganze aber doch auf Font icons beschränkt halten, also keine grafik icons einbinden, andere fonts wären natürlich möglich.

**Comment by sigi2345** [comment]
> Hi!
> 
> sorry, habe die nachricht jetzt erst gesehen....
> Ich komme mit den derzeitigen möglichkeiten/icons ganz gut aus, aber wenn die ideen/vorschläge hast können wir gerne reden, auch pull requests werden gerne angenommen.
> Ich möchte das ganze aber doch auf Font icons beschränkt halten, also keine grafik icons einbinden, andere fonts wären natürlich möglich.

Ok, Danke............
